In [3]:
import numpy as np

def modinv(a, m):
    return next(x for x in range(1, m) if a*x%m==1)

def matinv(A):
    a,b,c,d,e,f,g,h,i = A.flatten().astype(int)
    det = int(round(np.linalg.det(A)))%26
    adj = np.array([[e*i-f*h,c*h-b*i,b*f-c*e],[f*g-d*i,a*i-c*g,c*d-a*f],[d*h-e*g,b*g-a*h,a*e-b*d]])
    return (modinv(det,26)*adj)%26

def hill(msg, key):
    K = np.array([[ord(key[i*3+j])-65 for j in range(3)] for i in range(3)])
    M = np.array([[ord(msg[i])-65] for i in range(3)])

    print('Key Matrix:')
    for r in K: print(r.tolist())
    print('Message Matrix:')
    for r in M: print(r.tolist())

    C = (K@M)%26
    print('Cipher Matrix:')
    for r in C: print(r.tolist())
    print('Ciphertext:', ''.join(chr(C[i][0]+65) for i in range(3)))

    inv = matinv(K).astype(int)
    print('Inverse matrix modulo 26:')
    print(inv)

    D = (inv@C)%26
    print('Decrypted Matrix:')
    for r in D: print(r.tolist())
    print('Decrypted Text:', ''.join(chr(int(D[i][0])+65) for i in range(3)))

hill('MOR', 'RVCRSCFVT')

Key Matrix:
[17, 21, 2]
[17, 18, 2]
[5, 21, 19]
Message Matrix:
[12]
[14]
[17]
Cipher Matrix:
[12]
[22]
[1]
Ciphertext: MWB
Inverse matrix modulo 26:
[[ 4 15 24]
 [ 9 17  0]
 [15  6 17]]
Decrypted Matrix:
[12]
[14]
[17]
Decrypted Text: MOR
